# Start from the official Golang base image
FROM golang:1.21-alpine as builder

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy go mod and sum files
COPY cmd/ ./cmd
COPY internal/ ./internal

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

RUN go build -o main ./cmd/main.go

# Copy the source code
COPY . .

# Start a new stage from scratch
FROM alpine:latest  

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
