# Start from the official Golang base image
FROM golang:1.21-alpine as builder

# Set the Current Working Directory inside the container
WORKDIR /root

# Copy go mod and sum files
COPY back .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Build the binary
RUN go build -o back cmd/main.go

# Start a new stage from scratch
FROM alpine:latest

WORKDIR /root

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /root/back .
COPY --from=builder /root/config.json .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./back"]
