FROM node:16-alpine as builder

WORKDIR /app

COPY . .

RUN npm install --silent --no-progress --no-audit --no-optional --no-fund && npm run build

FROM nginx:1.21-alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
